### ISSUE TITLE
Remove node and yarn as prerequisites

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-development-platform#18]
The README lists `node` and `yarn` as prerequisites, but I'm not sure we ever actually use them directly in the host OS. I think it's possible to just have docker handle  everything. I am able to run a full reaction 2.0 stack without having them installed in the host OS. Now there could be supporting scripts we sometimes run that need them in one of the repos, but maybe not?

**Comment by focusaurus** [comment]
I guess we should also document `make` as a prerequisite while we're at it.

**Comment by aldeed** [comment]
We should recommend to `yarn install --dev` on the host machine in order for IDE eslint highlighting and such to work properly. Not sure if Yarn can be installed without Node.

Agree it should list `make`

**Comment by aldeed** [comment]
Technically that recommendation would be per-project; some projects might not even use Yarn or Node. Not sure whether that means it should be listed here or not. It's not a dependency of _this_ project

**Comment by focusaurus** [comment]
Related comment from [this issue](https://github.com/reactioncommerce/reaction-platform/issues/41#issuecomment-453761146)

> Why does your makefile utilize the hosts npm/yarn environment? As this is only for installing packages, couldn't that be done within with an disposable container or would that entail any drawbacks? I could make a PR if you want.
