### ISSUE TITLE
Pluggable Validation Hook for System Check

### ISSUE THREAD

**Issue by ticean** [reactioncommerce/reaction-development-platform#24]
## Problem Overview
The Reaction Platform project loosely binds together several projects in development that run in coordination as a complete system. By nature a distributed system is complicated and troubleshooting is more difficult than a monolith. This proposed improvement will provide tooling to understand the state of the system and identify issues that might prevent successful startup.

### Background
The `Makefile` in this project is fairly sophisticated because it contains dynamic programming. But beyond that, it's actually performing simple tasks. It checks out a set of git projects and runs Docker Compose command inside those project directories. It also invokes scripts within each configured project at specific lifecycle points, when those scripts exist. The process happily moves on when the project hook scripts do not exist.

### Validation Target

Create a new `make` target that will enumerate over each project and run a validation script.

This would follow the spirit of the `reaction-platform` project. The checks would be delegated to the individual projects. The maintainers of each project know what they need in order to run and can script the necessary checks.

The checks should help the user understand if anything has gone wrong. The best case would be to help the user understand how to fix it. Otherwise, it should provide enough information for others to help support new users.

#### When would it run?

The target would only run when manually invoked.

The script would need a running system. The user would need to run it manually with something like `make validate`. (Alternative naming suggestions welcome.) The new task should depend on the full system start which would automatically invoke a full system start. This would retain a single-command start while making a system check optional.

**Rejected Alternative:** The system check could be invoked after the `post-system-start` hooks on all projects but this would add to startup time and output noise. I think it's better to make it an optional step to run only when problems are encountered.

### Support in Sub Projects

Each project should add a `.reaction/project-hooks/validation-hook`.

The hook should call task(s) within the project that would perform the system checks. Common tasks would include health checks, OAuth Client validations and service dependency checks. Projects could implement anything they need.

### Handling Failures

For the first version, scripts can fail fast.

When a validation script encounters an error it should print a readable error for the user.

**Alternative:** Validation scripts output their errors for aggregation. The final aggregation is presented to the user at the end. All failed checks are visible at once. This would be a better experience but would also require more work to aggregate in the make task.

**Comment by ticean** [comment]
This idea didn't get traction, so I'm closing for now.

**Comment by focusaurus** [comment]
Note I recently started another round of work toward this. I was basically parsing `docker ps` output and trying to make sure the necessary containers were running. Still think it's valuable to do this and to have each project own its own status/health check scripts. Would like to see this restored into a backlog at some point but if not near term so be it.

**Comment by ticean** [comment]
Oh, that's great to hear @focusaurus. I'd really like to see us implement something. We can reopen and move to a backlog. I closed while doing some personal housecleaning, I have a huge backlog of issues that appear in my Github issues list and I'm trying to get them cleaned up so the page is meaningful to me and I don't think I'll get to this soon.

**Comment by delagroove** [comment]
Closing due to bandwidth issues
