### ISSUE TITLE
make: *** [reaction-hydra] Error 1

### ISSUE THREAD

**Issue by bantingGamer** [reactioncommerce/reaction-development-platform#45]
**## Issue Description**
running the **make** command produces the following **errors**:

```
if [ ! -d "reaction-hydra" ] ; then git clone "git@github.com:/reactioncommerce/reaction-hydra.git" "reaction-hydra"; cd reaction-hydra && git checkout "master"; fi
Cloning into 'reaction-hydra'...
ssh: Could not resolve hostname github.com;c: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/usr/bin/sh: line 0: cd: reaction-hydra: No such file or directory
Makefile:133: recipe for target 'reaction-hydra' failed
make: *** [reaction-hydra] Error 1
```

**## Steps to Reproduce**
1.  Install Docker 
2.  configure A GitHub account with a configured SSH key
3. git clone git@github.com:reactioncommerce/reaction-platform.git
4. cd reaction-platform
5. make

**### Versions**
windows 10
docker Version 2.0.0.2 (30215)

**Comment by ahmadRagheb** [comment]
i have the same issue too !!!!!!!!!!!

**Comment by ahmadRagheb** [comment]
i solve mine .. im using ubunut linux .. docker run with sudo and when i do make ? the docker demaon doesn't run  so i run with ` sudo make ` .. git dosn't work this ways -- " this is the same error you get "
i have make docker run without sudo for the current user .. it works for me 
https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue

**Comment by DKAtgit** [comment]
I am also getting Error while running make for reaction-hydra

OS: Windows 10
Docker : Docker version 18.09.2, build 6247962


"Makefile:320: warning: ignoring old recipe for target 'destroy-reaction-next-starterkit'
60e35c03d21045e04226cf8f933deab26af1fef7b9515972f7bc1134f1c9235d
1ddf22e65ea8a072f9e173c343f659b17626bdd5e66c6b1fb2f59210762fc672
6403988ffb57ddf38fa9efdf0e54d88a2d24ccb6ab18d4214a377f0df439b8e7
-e was unexpected at this time.
make: *** [Makefile:166: prebuild-reaction-hydra] Error 255 "

**Comment by bekliev** [comment]
Me too, how to fix this issue?

OS: Win10 (latest build)

```bash
PS C:\Projects\reaction-platform> make
497e8eebcf04439ca11161dd5c8d3b884289fbe725289bc458df045e0fb66314
e6234a5a980aff1a5c37962d164005c852a1ddeb55ef90db6430b94748991d30
cdc0b9cd0b32988e25729705a41039b4c7662f021468b66f84a65d2371556cd1
-e was unexpected at this time.
make: *** [prebuild-reaction-hydra] Error 255```

**Comment by Fl4zher** [comment]
Same issue here. 
Any solutions? 
Also Win10

**Comment by aldeed** [comment]
Windows development is not currently supported, but you may have luck trying on the Linux Subsystem for Windows.

**Comment by Allanbikundo** [comment]
Hey the error is still there 

Error response from daemon: network with name reaction.localhost already exists
Removed docker development symlink for reaction-hydra
Running pre-build hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
postgres uses an image, skipping
hydra-migrate uses an image, skipping
hydra uses an image, skipping
Running post-build hook script for reaction-hydra.
reaction-hydra post-build script invoked.
Pulling postgres      ... done
Pulling hydra-migrate ... done
Pulling hydra         ... done
reaction-hydra_postgres_1 is up-to-date
Starting reaction-hydra_hydra-migrate_1 ... done
reaction-hydra_hydra_1 is up-to-date
Running post-project-start hook script for reaction-hydra.
reaction-hydra post-project-start script invoked.
if [ ! -d "reaction" ] ; then git clone "git@github.com:/reactioncommerce/reaction.git" "reaction"; cd reaction && git checkout "v3.4.0"; fi
Cloning into 'reaction'...
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/bin/sh: 1: cd: can't cd to reaction
Makefile:159: recipe for target 'reaction' failed
make: *** [reaction] Error 2

**Comment by Allanbikundo** [comment]
My os is ubuntu 18
