### ISSUE TITLE
Unable to access the GraphQL API

### ISSUE THREAD

**Issue by aktywnitu** [reactioncommerce/reaction-development-platform#50]
Are you looking for help with getting started on Reaction? Please visit our [Reaction documentation](https://docs.reactioncommerce.com/reaction-docs/master/getting-started-developing-with-reaction).

## Prerequisites
* [x ] Are you running the latest version?
* [ ] Are you able to consistently reproduce the issue?
* [x ] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
After installing Reaction commerce and opening first page I received error:
"Unable to access the GraphQL API. Is it running and accessible at http://reaction.api.reaction.localhost:3000/graphql-alpha from the Storefront UI server?"

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Install Reaction commerce via reaction-platform in docker environment.
2. Open first page.
3. See the logs: reaction-next-starterkit$ docker-compose logs -f

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions

**Comment by adrienshen** [comment]
Second this. Seems recent.

**Comment by makhokit** [comment]
Any update?

**Comment by Jesperskate** [comment]
+1

**Comment by kromuch** [comment]
+1

**Comment by Jesperskate** [comment]
Hi all! I found a nice tutorial as a workaround: https://medium.com/dominikbittl/how-to-get-started-with-meteor-and-reactioncommerce-within-a-vagrant-box-on-macos-771ef86c8398

**Comment by mauber91** [comment]
I'm also having this issue :(

**Comment by gddabe** [comment]
+1

**Comment by HolaMan** [comment]
+1

**Comment by kmyn** [comment]
+1

**Comment by RaminMammadzada** [comment]
+1

**Comment by RaminMammadzada** [comment]
+1

**Comment by aldeed** [comment]
In general, the solution to this error is to check the API service logs and try to get it to start. You may just need to restart the Docker service or there may be more information in the error messages in the logs. From within the platform directory, this is how you restart it:

```sh
make stop-reaction
make start-reaction
```
