### ISSUE TITLE
Facilitate shared env files

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-development-platform#53]
## Feature Request

We'd like a mechanism for teams to create and managed environment variable files with settings and secrets, and easily and securely incorporate that data into local development environments.

## Motivation

- Sensible defaults for local development are usually but not always sufficient
- Some values really need to vary per-project or per-team or per-developer
  - Examples: third party service API keys, cloud specific details like S3 bucket paths
- It's easy for managing this to become a tedious, error-prone, and frustrating experience
  - Teams can lose track of the full up-to-date list of environment variables
  - The knowledge of the current correct values for each setting can become distributed across different developers
- Currently we don't give timely feedback when values or wrong (although we plan to directly address this separately), so this can cause a developer to go through multiple rounds of wait a long time, get an error message relating to some environment variable, try to correct it, wait a long time, etc. This is a very frustrating experience. It's also very inefficient in terms of developer time.

## ENV_PATH solution design

Each project changes its `docker-compose.yml` file to take advantage of some supported features:

- docker-compose supports a list of env files
- the paths to those files can be stored in environment variables
  - Specifying defaults with bash syntax is supported
- docker-compose handles loading in order with later files overwriting values from earlier files

For example, in core `reaction` we could have this section in `docker-compose.yml`

```yaml
services:
  reaction:
    env_file:
      - "${REACTION_ENV_PATH-./.env}"
      - "${REACTION_ENV2_PATH-./.env2}"
…
```

Developers could configure a custom path by setting the corresponding environment variables. This mechanism should support

- Keybase filesystem paths like `/keybase/team/acme/.env.reaction`
- Dropbox when mounted as a local filesystem
- Google drive when mounted as a local filesystem
  - I use google-drive-ocaml-fuse for this on linux
- Other local files preconfigured for a particular project or feature branch

**Side Benefit**

- This would at least partially also facilitate easier switching between divergent code branches or environments
  - If a developer is working on a new feature branch that requires some new/different values, they can have `REACTION_ENV2_PATH=.env2-feature-a` and when switching tasks and checking out different git branches, it's just a matter of setting or unsetting that environment variable

**Implementation Notes**

- Files at these paths **must exist** to avoid a `docker-compose` error (but they can be empty) so `bin/setup` or other script should ensure at least there exist empty files in the case no `REACTION_ENV_PATH` environment variables are set
- The idea would be `REACTION_ENV_PATH` could be team-shared defaults and developer-specific overrides to that could live at `REACTION_ENV2_PATH`
- I think ENV and ENV2 is probably the right number, but I could likely be convinced that either just 1 is sufficient or we should support 3 or 4.

**Open Questions**

- Given our general preference for independent microservices, each project would need to have a unique variable name so `REACTION_ENV_PATH`, `STOREFRONT_ENV_PATH`, `SEARCH_ENV_PATH` etc to avoid collisions.
- However, maybe it's worth considering whether the whole platform should share a single file with unique env var names.

## Symlink solution design

Maybe just documenting/testing that the `.env` and `.env2` files being symlinks is sufficient. I have locally tested (on linux) that symlinking my `.env` to a file in keybase filesystem works fine.

**Open Questions**

- How would we want to integrate with a fresh clone and "first big make" flow?
- Split up the steps?
  - `make checkout`
  - Script to set up the symlinks
  - `make start`
- Support specifying as env vars on your command line?
  - `REACTION_ENV_PATH=/path/to/.env make start`
    - Scripts then set up the symlink for you

**Caveats**

- Would require a bit more skill/comfort from developers with symlink management on macos and linux  
- Could potentially be problematic is we start supporting windows development again
- I suspect symlinking to a keybase filesystem file might lead to obscure error messages if you try to start reaction-platform when keybase filesystem isn't mounted and available.

## Other concerns

- Need to think about risk of disrupting your team when making changes to the env files. Need to try to be backward compatible, deprecate old names, not remove them until all work on older branches that reference them is complete, etc.
  - Could maybe use timestamp file naming conventions so developers can update their own symlinks when ready: `/keybase/team/acme/.env.reaction-2019-03-05`
- Need to understand dependency on cloud filesystems may prevent or hamper offline development work
  - Need to also understand if developers copy files from encrypted cloud filesystems to local to support offline work, they are less likely to be encrypted at rest

**Comment by ticean** [comment]
There's a third option - a script that can copy environment variables from a custom location to `.env`.

## Custom ENV Setup

We currently have an `bin/setup` in each project that copies variables from an `.env.example` -> `.env`. The only problem is that the script is hardcoded to do this from specific files.

A general utility that could copy env from and to any configurable files would be much more flexible.

A setup with that ability could be used by platform tooling to copy from an external location when configured to do so. The external configuration could contain secrets shared by the team.

#### Example
I drafted an example of such a script in https://github.com/reactioncommerce/reaction/pull/5035.

#### Advantages

* It's the same model as the usual `bin/setup`. Env are copied, as they are usually done within in a project. This allows the developer to make local changes as needed without tooling clobbering those changes.
* None of the disadvantages of symlinking. Expect conflicts when a team is symlinking a shared filesystem.

#### Open Questions

* It was easy to use a script like this in the `reaction` project. We'd need to figure out the right way to tool it in the platform. We'll need to select where the script would run. From the platform at the top, or inside each project?
* Determine how to configure a custom env location for each project. This could be done with an explicit, per-project config. Or, via pathing convention and a single config.

**Comment by focusaurus** [comment]
> A setup with that ability could be used by platform tooling to copy from an external location when configured to do so

How are you thinking this configuration would take place?

What about if in `config.local.mk` there's a repo there just to provide environment-specific scripting and tooling?

```make
define SUBPROJECT_REPOS
git@github.com:/example-company/reaction-local-dev.git,reaction-local-dev,master \
...(more repos omitted)
endef
```
That repo has scripts for the standard reaction-platform lifecycle hooks and they do whatever they need to do, check prereqs, copy env files, etc.

**Comment by delagroove** [comment]
closing due to bandwidth issues
