### ISSUE TITLE
Support release tags and upgrades

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-development-platform#57]
## Issue Description

As we get ready for the final 2.0.0 release and subsequent semver releases following that, I think we need to make sure we have a solid mechanism including documentation and reaction-platform code to how we expect upgrading to newer releases. We have `make checkout` but I think we need to work through some more things:

- Repos that need to fetch new tags
- dealing with uncommitted changes in local work areas

**Comment by ticean** [comment]
A good chunk of this (maybe all?) was addressed in #114. @focusaurus think we can close this now?

> Repos that need to fetch new tags

There's nothing that automatically addresses this, but it is possible to switch to a new configuration file by updating the local repo, or symlinking the local config. After doing that, you'd probably want to move to the next step.

> Dealing with uncommitted changes in local work areas.

#114 introduced `make update-checkouts`. It makes sure that each poject has the configured git ref checked out. The command is safe. It will halt if there are uncommitted changes in git before doing anything. You may manually commit, stash or drop any git diffs when that happens.

**Comment by delagroove** [comment]
make update-checkouts is part of the make commands now
please follow up in #191 for an update on make commands
