### ISSUE TITLE
Add Segment tracking from CLI to RP

### ISSUE THREAD

**Issue by machikoyasuda** [reactioncommerce/reaction-development-platform#60]
As of Reaction 2.0, the https://github.com/reactioncommerce/reaction-cli is **removed** as a dependency. For 1.x users, the https://github.com/reactioncommerce/reaction-cli will no longer be updated.

Instead of having Segment as a part of the CLI, we'd like to add the Segment features from the CLI into Reaction Platform. Ask @cindyfirestone for credentials for Segment & other specifics on data to be tracked.

Code from CLI: https://github.com/reactioncommerce/reaction-cli/blob/master/src/utils/analytics.js

cc / @cshivaratri @cindyfirestone

**Comment by delagroove** [comment]
closing due to bandwidth issues
