### ISSUE TITLE
Installation/Startup error

### ISSUE THREAD

**Issue by kmyn** [reactioncommerce/reaction-development-platform#68]
## Prerequisites
* [ Y] Are you running the latest version?
* [ Y] Are you able to consistently reproduce the issue?
* [ Y] Did you search the issue queue for existing issue? [Search issues]  (https://github.com/reactioncommerce/reaction/issues)

## Issue Description

`reaction_reaction` docker container fails to start with the below error:
```
Setting up plugin imports...

Installing dependencies for email-templates...

npm WARN checkPermissions Missing write access to /opt/reaction/src/imports/plugins/included/email-templates
npm WARN reaction-plugin-email-templates@1.0.0 No repository field.

npm ERR! path /opt/reaction/src/imports/plugins/included/email-templates
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/opt/reaction/src/imports/plugins/included/email-templates'
npm ERR!  { Error: EACCES: permission denied, access '/opt/reaction/src/imports/plugins/included/email-templates'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/reaction/src/imports/plugins/included/email-templates\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/reaction/src/imports/plugins/included/email-templates' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
`make start` on a clean install

Platform is CentOS 7

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions

**Comment by koverboy** [comment]
up

Same issue

**Comment by KaySchneider** [comment]
On CentOs this is a problem with the docker volume.  
CentOs is using SELinux and for that you have to use the SeLinux labels(:z or :Z) when mounting volumes. As example (docker-compose.yml file example):
````
... 
volumes:
      - .:/opt/reaction/src:cached:Z
      - reaction_meteor_local:/opt/reaction/src/.meteor/local:z
      - reaction_node_modules:/opt/reaction/src/node_modules:z

````   


More information about here:   
https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
